export const SWITCH_ALL_WALLETS = "SWITCH_ALL_WALLETS";
export const SWITCH_NEW_WALLET = "SWITCH_NEW_WALLET";
export const SWITCH_CHECK_BALANCE = "SWITCH_CHECK_BALANCE";
export const SWITCH_ADD_FUNDS = "SWITCH_ADD_FUNDS";
export const SWITCH_SPEND_FUNDS = "SWITCH_SPEND_FUNDS";
export const SWITCH_ALL_TRANSACTIONS = "SWITCH_ALL_TRANSACTIONS";

